### ISSUE TITLE
7.6.0 has released.

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-bt#11]
**What type of your feature request?**  

- [x] Add new features
- [x] Improve current features

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by GFangyu** [comment]
#### ansible-bt aliyun-centos 
````
"end_check_versions.stdout_lines": [
        "bt version: 7.6.0", 
        "System version: CentOS 7.9", 
        "Image name: btfangyutest-CentOS7.9"
    ]
````

**Comment by GFangyu** [comment]
#### ansible-bt aliyun-centos 
````
"end_check_versions.stdout_lines": [
        "bt version: 7.6.0", 
        "System version: CentOS 7.9", 
        "Image name: btfangyutest-CentOS7.9"
    ]
````

**Comment by geraintlyu** [comment]
the version of bt-int is error!
![bthao](https://user-images.githubusercontent.com/53968450/126022773-eee0efce-c273-4b9c-85bb-4d653f131e2b.png)

![bt](https://user-images.githubusercontent.com/53968450/126022702-8add8c45-feb6-4179-aece-017f8d2e2d50.png)

**Comment by geraintlyu** [comment]
the version of bt-chinese is ok!
![bt-c](https://user-images.githubusercontent.com/53968450/126023241-ad5a69c2-d45b-4666-aa29-9e3d349bd392.png)
![bt-chinese](https://user-images.githubusercontent.com/53968450/126023244-243c94f1-c226-4689-a99b-60dd7693bec3.png)
